version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    parallelism: 15
    docker:
      - image: cimg/base:2021.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"

  test:
    machine:
        image: ubuntu-2004:202008-01
    parallelism: 15
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
